name: stoyco_partners_shared
description: "A new Flutter package project."
version: 2.0.2
homepage: null

environment:
  sdk: ^3.10.1
  flutter: ">=1.17.0"

dependencies:
  carousel_slider: ^5.1.1
  country_flags: ^4.1.1
  cupertino_icons: ^1.0.6
  either_dart: ^1.0.0
  equatable: ^2.0.5
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_native_splash: ^2.4.7
  flutter_statusbarcolor_ns: ^0.6.0
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  get: ^4.6.6
  get_storage: ^2.1.1
  intl_phone_field: ^3.2.0
  json_annotation: ^4.10.0
  pinput: ^6.0.1
  reactive_forms: ^18.2.2
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  skeletonizer: ^2.1.2
  logger: ^2.6.2

dev_dependencies:
  build_runner: ^2.4.9
  flutter_gen: ^5.4.0
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - lib/assets/colors/
    - lib/assets/fonts/
    - lib/assets/images/
    - lib/assets/icons/
    - lib/assets/icons/common/

  fonts:
    - family: Gilroy
      fonts:
        - asset: lib/assets/fonts/gilroy/Gilroy-Thin.ttf
          weight: 100
        - asset: lib/assets/fonts/gilroy/Gilroy-UltraLight.ttf
          weight: 200
        - asset: lib/assets/fonts/gilroy/Gilroy-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/gilroy/Gilroy-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/gilroy/Gilroy-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/gilroy/Gilroy-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/gilroy/Gilroy-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/gilroy/Gilroy-ExtraBold.ttf
          weight: 800
        - asset: lib/assets/fonts/gilroy/Gilroy-Black.ttf
          weight: 900

    - family: Akkurat
      fonts:
        - asset: lib/assets/fonts/akkurat/AkkuratMono-Regular.ttf

flutter_gen:
  output: lib/design/utils/tokens/gen
  integrations:
    flutter_svg: true
  assets:
    enabled: true
    outputs:
      class_name: StoycoAssetsToken
  fonts:
    enabled: true
    outputs:
      class_name: StoycoFontFamilyToken
  colors:
    enabled: true
    outputs:
      class_name: StoycoColorsToken
    inputs:
      - lib/assets/colors/colors.xml
